name = "public-worker"
main = "src/index.js"
compatibility_date = "2025-10-22"

# D1 Database Bindings
[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "1da591ba-005a-41ef-86dd-f8755b06092d"

# KV Namespace Bindings
[[kv_namespaces]]
binding = "KV"
id = "3ed6c618f391422eb4ab3e2be270c156"

# Environment variables
[vars]
ALLOWED_ORIGINS = "*"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true